services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: "docker.io/library/postgres:16"
    command:
      - postgres
      - -c
      - shared_buffers=1GB
      - -c
      - maintenance_work_mem=512MB
    volumes:
      - ./db-data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
